# -*- coding: utf-8 -*-
"""week4(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19VQfNfj69NSo-T397v5Fg7Z78zrw9XIL
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

print("Path to dataset files:", path)

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix
)

# List files in the downloaded directory
files = os.listdir(path)
csv_file = None
for file in files:
    if file.endswith(".csv"):
        csv_file = os.path.join(path, file)
        break

if csv_file:
    df = pd.read_csv(csv_file, encoding="latin-1")
    if {"v1", "v2"}.issubset(df.columns):
        df = df[["v1", "v2"]].rename(columns={"v1": "label", "v2": "text"})
    elif {"label", "text"}.issubset(df.columns):
        df = df[["label", "text"]]
    else:
        raise ValueError("Expected columns v1/v2 or label/text in the CSV.")

    df = df.dropna(subset=["label", "text"]).copy()
    df["text"] = df["text"].astype(str).str.strip()

    # Map labels: ham->0, spam->1
    label_map = {"ham": 0, "spam": 1, 0: 0, 1: 1}
    df["target"] = df["label"].map(label_map)
    assert df["target"].isin([0, 1]).all(), "Label mapping failed."

    print("\nDataset summary")
    print("Total samples:", len(df))
    print(df["label"].value_counts())
else:
    print("No CSV file found in the downloaded dataset directory.")

# 3) Train / test split (stratified)
X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["target"], test_size=0.2, random_state=42, stratify=df["target"]
)

# 4) Build pipelines
#    TF-IDF + Naive Bayes; TF-IDF + Logistic Regression
tfidf = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2),
    min_df=2
)

nb_pipeline = Pipeline([
    ("tfidf", tfidf),
    ("clf", MultinomialNB(alpha=0.1)),
])

lr_pipeline = Pipeline([
    ("tfidf", tfidf),
    ("clf", LogisticRegression(max_iter=2000, C=4.0)),
])

def fit_eval(name, pipe, X_train, X_test, y_train, y_test, plot=True):
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print(f"\n=== {name} ===")
    print(f"Accuracy: {acc:.4f}")
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["ham", "spam"], digits=4))

    if plot:
        cm = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(4, 3))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                    xticklabels=["ham", "spam"], yticklabels=["ham", "spam"])
        plt.title(f"Confusion Matrix - {name}")
        plt.xlabel("Predicted")
        plt.ylabel("True")
        plt.tight_layout()
        plt.show()

    return y_pred, acc

# 6) Train & evaluate Naive Bayes
y_pred_nb, acc_nb = fit_eval("Multinomial Naive Bayes (TF-IDF)", nb_pipeline,
                             X_train, X_test, y_train, y_test, plot=True)

#    Show 5 misclassified messages
mis_idx = np.where(y_pred_nb != y_test.to_numpy())[0]
print("\nFive misclassified messages:")
for i in mis_idx[:5]:
    print("-" * 60)
    print("TEXT     :", X_test.iloc[i])
    print("TRUE     :", "spam" if y_test.iloc[i] == 1 else "ham")
    print("PREDICTED:", "spam" if y_pred_nb[i] == 1 else "ham")

# 7) Compare with Logistic Regression
y_pred_lr, acc_lr = fit_eval("Logistic Regression (TF-IDF)", lr_pipeline,
                             X_train, X_test, y_train, y_test, plot=True)