USE quanlythuvien;

-- ---------- QUESTION 1: LIỆT KÊ TẤT CẢ SÁCH CÓ TRONG HỆ THỐNG  ----------
SELECT S.MASACH, S.TENSACH, TL.TENTHELOAI
FROM SACH S JOIN THELOAI TL ON S.MATHELOAI = TL.MATHELOAI;

-- ---------- QUESTION 2: TỔNG HỢP CÁC THẺ ĐỘC GIẢ TRONG NĂM 2023 ----------
SELECT TDG.MATHE, TDG.HOTEN
FROM THEDOCGIA TDG
WHERE TDG.NGAYCAP = 2023;

-- ---------- QUESTION 3: TỔNG HỢP CÁC SÁCH 'VĂN HỌC' ----------
SELECT *
FROM SACH S LEFT JOIN THELOAI TL ON S.MATHELOAI = TL.MATHELOAI
WHERE TL.TENTHELOAI = 'VĂN HỌC';

-- ---------- QUESTION 4: TỔNG HỢP CÁC SÁCH ĐƯỢC THỰC HIỆN BỞI NHÂN VIÊN 'PHẠM MINH' ----------
SELECT * 
FROM PHIEUMUON PM JOIN NHANVIEN NV ON PM.MANV = NV.MANV
WHERE NV.HOTEN = 'Phạm Minh';

-- ---------- QUESTION 5: TỔNG HỢP SỐ LƯỢNG ĐƯỢC MƯỢN (BAO NHIÊU NNGƯỜI MƯỢN), TỔNG SỐ ĐƯỢC MƯỢN CỦA CÁC SÁCH ĐƯỢC MƯỢN ----------
SELECT S.TENSACH, COUNT(DISTINCT CT.MAPHIEU) AS SOLUONGMUON, SUM(CT.SOLUONG) AS TONGSODUOCMUON
FROM SACH S JOIN CHITIETPM CT ON S.MASACH = CT.MASACH
GROUP BY S.TENSACH;

-- ---------- QUESTION 6 ----------
SELECT 
FROM 
GROUP BY 
HAVING 



-- ---------- QUESTION 7 ----------
SELECT 
FROM 
GROUP BY 
HAVING 



-- ---------- QUESTION 8 ----------


