import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { useNavigate } from "react-router-dom";

export default function AuthCallback() {
    const navigate = useNavigate();
    const [message, setMessage] = useState("Signing you in...");

    useEffect(() => {
        const handleCallback = async () => {
            const { data: { session }, error } = await supabase.auth.getSession();

            if (error || !session) {
                console.error("Callback check failed", error);
                navigate("/login");
                return;
            }

            // Check if profile is "complete" (i.e. not auto-generated user_xxx)
            // We use the backend /me call or direct DB check if possible, calling /me is safer
            try {
                const res = await fetch(`${import.meta.env.VITE_API_BASE_URL}/api/v1/me`, {
                    headers: { Authorization: `Bearer ${session.access_token}` },
                });

                if (res.ok) {
                    const json = await res.json();
                    const profile = json.data?.profile;

                    // Logic: If username starts with 'user_' and follows uuid pattern (roughly), we assume it's auto-generated
                    // Or we can check if password is set? (Supabase doesn't expose this easily)
                    // Simple check: Is username likely auto-generated?
                    const isAutoGenerated = profile.username.startsWith("user_") && profile.username.length >= 13; // user_ + 8 chars

                    if (isAutoGenerated) {
                        navigate("/complete-profile");
                    } else {
                        navigate("/feed");
                    }
                } else {
                    // Fail safe
                    navigate("/feed");
                }
            } catch (e) {
                console.error(e);
                navigate("/feed");
            }
        };

        handleCallback();
    }, [navigate]);

    return (
        <div style={{ display: "flex", justifyContent: "center", alignItems: "center", height: "100vh" }}>
            <p>{message}</p>
        </div>
    );
}
