# -*- coding: utf-8 -*-
"""week4(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HS233VXeq65-RVu5SasM42cqc36Hfeay

# **1. Import**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    accuracy_score
)

from sklearn.pipeline import Pipeline

"""# **2. Load**"""

iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.Series(iris.target, name="target")  # 0=setosa, 1=versicolor, 2=virginica
target_names = iris.target_names

# Quick survey
print("- Shape:", X.shape)
print("- First 5 rows:\n", X.head(), "\n")

"""# **3. Train & Evaluate**


"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)


def train_and_evaluate(model, X_train, X_test, y_train, y_test, title=""):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    print(f"\n=== {title} ===")
    print(f"Accuracy: {acc:.4f}")

    print("\nClassification Summary:")
    print(classification_report(y_test, y_pred, target_names=target_names, digits=4))

    cm = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=target_names)
    fig, ax = plt.subplots(figsize=(4, 4))
    disp.plot(cmap="Blues", ax=ax, colorbar=False)
    ax.set_title(f"Confusion Matrix - {title}")
    plt.show()

    return acc

# Train Naive Bayes on unscaled data
nb = GaussianNB()
acc_unscaled = train_and_evaluate(nb, X_train, X_test, y_train, y_test, title="GaussianNB (Unscaled)")

# scaling is not strictly required but can help numerical stability and sometimes accuracy.
pipeline_scaled = Pipeline([
    ("scaler", StandardScaler()),
    ("nb", GaussianNB())
])

acc_scaled = train_and_evaluate(
    pipeline_scaled, X_train, X_test, y_train, y_test, title="GaussianNB + StandardScaler"
)

"""# **4. Results**"""

print("\nSUMMARY")
print(f"- Test Accuracy (Unscaled): {acc_unscaled:.4f}")
print(f"- Test Accuracy (Scaled)  : {acc_scaled:.4f}")

"""# **Giải thích Kết quả**

* **Gaussian** giả định rằng các đặc trưng (features) tuân theo phân phối chuẩn có điều kiện cho mỗi lớp. Quá trình chuẩn hóa (StandardScaler) biến đổi dữ liệu sao cho nó có trung bình bằng 0 và độ lệch chuẩn bằng 1. Việc này không thay đổi hình dạng cơ bản của phân phối dữ liệu, mà chỉ thay đổi tỷ lệ và vị trí của nó. Do đó, đối với mô hình Naive Bayes Gaussian, việc thay đổi tỷ lệ và vị trí này thường không ảnh hưởng đến ranh giới quyết định giữa các lớp, miễn là các giả định về phân phối chuẩn vẫn được giữ.
* **Ranh giới quyết định của Naive Bayes**: Ranh giới quyết định của mô hình Naive Bayes Gaussian dựa trên việc so sánh các xác suất logarit. Khi bạn chuẩn hóa dữ liệu, các giá trị đặc trưng thay đổi, nhưng tỷ lệ tương đối giữa các xác suất có điều kiện cho các lớp thường không thay đổi theo cách làm thay đổi kết quả phân loại cuối cùng.
* **Tập dữ liệu Iris**: Tập dữ liệu Iris là một tập dữ liệu tương đối "sạch" và các đặc trưng có sự phân tách rõ ràng giữa các lớp. Trong trường hợp này, ngay cả khi không chuẩn hóa, mô hình Naive Bayes Gaussian đã có thể tìm thấy ranh giới quyết định hiệu quả. Việc chuẩn hóa không mang lại lợi ích đáng kể để cải thiện hiệu suất phân loại.


"""