services:
  mysql:
    image: mysql:8.0
    container_name: company-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: companydb
      MYSQL_USER: companyuser
      MYSQL_PASSWORD: companypass
    ports:
      - "3307:3306"              # Host 3307 -> Container 3306
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: company-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

  node-app:
    build: .
    container_name: company-node
    restart: unless-stopped
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: companyuser
      DB_PASSWORD: companypass
      DB_NAME: companydb
    ports:
      - "3001:3000"
    depends_on:
      - mysql

volumes:
  db_data:
